- hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars.yml
  tasks:
    - include: task_java8_install.yml
    - include: task_tomcat_install.yml
    - include: task_httpd_install.yml
